<?php

class Zorahora{

	static  $zonas= [
			array('name'=>'America/Guayaquil', 'code'=>'(UTC-05:00) Guayaquil'),
			array('name'=>'America/Lima', 'code'=>'(UTC-05:00) Lima'),
		    array('name'=>'America/Adak','code'=>'(UTC-10:00) Adak'),
		    array('name'=>'America/Juneau', 'code'=>'(UTC-09:00) Juneau'),
		    array('name'=>'America/Nome', 'code'=>'(UTC-09:00) Nome'),
		    array('name'=>'America/Sitka', 'code'=>'(UTC-09:00) Sitka'),
		    array('name'=>'America/Yakutat', 'code'=>'(UTC-09:00) Yakutat'),
		    array('name'=>'America/Dawson', 'code'=>'(UTC-08:00) Dawson'),
		    array('name'=>'America/Los_Angeles', 'code'=>'(UTC-08:00) Los Angeles'),
		    array('name'=>'America/Metlakatla', 'code'=>'(UTC-08:00) Metlakatla'),
		    array('name'=>'America/Santa_Isabel', 'code'=>'(UTC-08:00) Santa Isabel'),
		    array('name'=>'America/Tijuana', 'code'=>'(UTC-08:00) Tijuana'),
		    array('name'=>'America/Vancouver', 'code'=>'(UTC-08:00) Vancouver'),
		    array('name'=>'America/Whitehorse', 'code'=>'(UTC-08:00) Whitehorse'),
		    array('name'=>'America/Boise', 'code'=>'(UTC-07:00) Boise'),
		    array('name'=>'America/Cambridge_Bay', 'code'=>'(UTC-07:00) Cambridge Bay'),
		    array('name'=>'America/Chihuahua', 'code'=>'(UTC-07:00) Chihuahua'),
		    array('name'=>'America/Creston', 'code'=>'(UTC-07:00) Creston'),
		    array('name'=>'America/Dawson_Creek', 'code'=>'(UTC-07:00) Dawson Creek'),
		    array('name'=>'America/Denver', 'code'=>'(UTC-07:00) Denver'),
		    array('name'=>'America/Edmonton', 'code'=>'(UTC-07:00) Edmonton'),
		    array('name'=>'America/Hermosillo', 'code'=>'(UTC-07:00) Hermosillo'),
		    array('name'=>'America/Inuvik', 'code'=>'(UTC-07:00) Inuvik'),
		    array('name'=>'America/Mazatlan', 'code'=>'(UTC-07:00) Mazatlan'),
		    array('name'=>'America/Ojinaga', 'code'=>'(UTC-07:00) Ojinaga'),
		    array('name'=>'America/Phoenix', 'code'=>'(UTC-07:00) Phoenix'),
		    array('name'=>'America/Shiprock', 'code'=>'(UTC-07:00) Shiprock'),
		    array('name'=>'America/Yellowknife', 'code'=>'(UTC-07:00) Yellowknife'),
		    array('name'=>'America/Bahia_Banderas', 'code'=>'(UTC-06:00) Bahia Banderas'),
		    array('name'=>'America/Belize', 'code'=>'(UTC-06:00) Belize'),
		    array('name'=>'America/North_Dakota/Beulah', 'code'=>'(UTC-06:00) Beulah'),
		    array('name'=>'America/Cancun', 'code'=>'(UTC-06:00) Cancun'),
		    array('name'=>'America/North_Dakota/Center', 'code'=>'(UTC-06:00) Center'),
		    array('name'=>'America/Chicago', 'code'=>'(UTC-06:00) Chicago'),
		    array('name'=>'America/Costa_Rica', 'code'=>'(UTC-06:00) Costa Rica'),
		    array('name'=>'America/El_Salvador', 'code'=>'(UTC-06:00) El Salvador'),
		    array('name'=>'America/Guatemala', 'code'=>'(UTC-06:00) Guatemala'),
		    array('name'=>'America/Indiana/Knox', 'code'=>'(UTC-06:00) Knox'),
		    array('name'=>'America/Managua', 'code'=>'(UTC-06:00) Managua'),
		    array('name'=>'America/Matamoros', 'code'=>'(UTC-06:00) Matamoros'),
		    array('name'=>'America/Menominee', 'code'=>'(UTC-06:00) Menominee'),
		    array('name'=>'America/Merida', 'code'=>'(UTC-06:00) Merida'),
		    array('name'=>'America/Mexico_City', 'code'=>'(UTC-06:00) Mexico City'),
		    array('name'=>'America/Monterrey', 'code'=>'(UTC-06:00) Monterrey'),
		    array('name'=>'America/North_Dakota/New_Salem', 'code'=>'(UTC-06:00) New Salem'),
		    array('name'=>'America/Rainy_River', 'code'=>'(UTC-06:00) Rainy River'),
		    array('name'=>'America/Rankin_Inlet', 'code'=>'(UTC-06:00) Rankin Inlet'),
		    array('name'=>'America/Regina', 'code'=>'(UTC-06:00) Regina'),
		    array('name'=>'America/Resolute', 'code'=>'(UTC-06:00) Resolute'),
		    array('name'=>'America/Swift_Current', 'code'=>'(UTC-06:00) Swift Current'),
		    array('name'=>'America/Tegucigalpa', 'code'=>'(UTC-06:00) Tegucigalpa'),
		    array('name'=>'America/Indiana/Tell_City', 'code'=>'(UTC-06:00) Tell City'),
		    array('name'=>'America/Winnipeg', 'code'=>'(UTC-06:00) Winnipeg'),
		    array('name'=>'America/Atikokan', 'code'=>'(UTC-05:00) Atikokan'),
		    array('name'=>'America/Bogota', 'code'=>'(UTC-05:00) Bogota'),
		    array('name'=>'America/Cayman', 'code'=>'(UTC-05:00) Cayman'),
		    array('name'=>'America/Detroit', 'code'=>'(UTC-05:00) Detroit'),
		    array('name'=>'America/Grand_Turk', 'code'=>'(UTC-05:00) Grand Turk'),		    
		    array('name'=>'America/Havana', 'code'=>'(UTC-05:00) Havana'),
		    array('name'=>'America/Indiana/Indianapolis', 'code'=>'(UTC-05:00) Indianapolis'),
		    array('name'=>'America/Iqaluit', 'code'=>'(UTC-05:00) Iqaluit'),
		    array('name'=>'America/Jamaica', 'code'=>'(UTC-05:00) Jamaica'),		    
		    array('name'=>'America/Kentucky/Louisville', 'code'=>'(UTC-05:00) Louisville'),
		    array('name'=>'America/Indiana/Marengo', 'code'=>'(UTC-05:00) Marengo'),
		    array('name'=>'America/Kentucky/Monticello', 'code'=>'(UTC-05:00) Monticello'),
		    array('name'=>'America/Montreal', 'code'=>'(UTC-05:00) Montreal'),
		    array('name'=>'America/Nassau', 'code'=>'(UTC-05:00) Nassau'),
		    array('name'=>'America/New_York', 'code'=>'(UTC-05:00) New York'),
		    array('name'=>'America/Nipigon', 'code'=>'(UTC-05:00) Nipigon'),
		    array('name'=>'America/Panama', 'code'=>'(UTC-05:00) Panama'),
		    array('name'=>'America/Pangnirtung', 'code'=>'(UTC-05:00) Pangnirtung'),
		    array('name'=>'America/Indiana/Petersburg', 'code'=>'(UTC-05:00) Petersburg'),
		    array('name'=>'America/Port-au-Prince', 'code'=>'(UTC-05:00) Port-au-Prince'),
		    array('name'=>'America/Thunder_Bay', 'code'=>'(UTC-05:00) Thunder Bay'),
		    array('name'=>'America/Toronto', 'code'=>'(UTC-05:00) Toronto'),
		    array('name'=>'America/Indiana/Vevay', 'code'=>'(UTC-05:00) Vevay'),
		    array('name'=>'America/Indiana/Vincennes', 'code'=>'(UTC-05:00) Vincennes'),
		    array('name'=>'America/Indiana/Winamac', 'code'=>'(UTC-05:00) Winamac'),
		    array('name'=>'America/Caracas', 'code'=>'(UTC-04:30) Caracas'),
		    array('name'=>'America/Anguilla', 'code'=>'(UTC-04:00) Anguilla'),
		    array('name'=>'America/Antigua', 'code'=>'(UTC-04:00) Antigua'),
		    array('name'=>'America/Aruba', 'code'=>'(UTC-04:00) Aruba'),
		    array('name'=>'America/Asuncion', 'code'=>'(UTC-04:00) Asuncion'),
		    array('name'=>'America/Barbados', 'code'=>'(UTC-04:00) Barbados'),
		    array('name'=>'America/Blanc-Sablon', 'code'=>'(UTC-04:00) Blanc-Sablon'),
		    array('name'=>'America/Boa_Vista', 'code'=>'(UTC-04:00) Boa Vista'),
		    array('name'=>'America/Campo_Grande', 'code'=>'(UTC-04:00) Campo Grande'),
		    array('name'=>'America/Cuiaba', 'code'=>'(UTC-04:00) Cuiaba'),
		    array('name'=>'America/Curacao', 'code'=>'(UTC-04:00) Curacao'),
		    array('name'=>'America/Dominica', 'code'=>'(UTC-04:00) Dominica'),
		    array('name'=>'America/Eirunepe', 'code'=>'(UTC-04:00) Eirunepe'),
		    array('name'=>'America/Glace_Bay', 'code'=>'(UTC-04:00) Glace Bay'),
		    array('name'=>'America/Goose_Bay', 'code'=>'(UTC-04:00) Goose Bay'),
		    array('name'=>'America/Grenada', 'code'=>'(UTC-04:00) Grenada'),
		    array('name'=>'America/Guadeloupe', 'code'=>'(UTC-04:00) Guadeloupe'),
		    array('name'=>'America/Guyana', 'code'=>'(UTC-04:00) Guyana'),
		    array('name'=>'America/Halifax', 'code'=>'(UTC-04:00) Halifax'),
		    array('name'=>'America/Kralendijk', 'code'=>'(UTC-04:00) Kralendijk'),
		    array('name'=>'America/La_Paz', 'code'=>'(UTC-04:00) La Paz'),
		    array('name'=>'America/Lower_Princes', 'code'=>'(UTC-04:00) Lower Princes'),
		    array('name'=>'America/Manaus', 'code'=>'(UTC-04:00) Manaus'),
		    array('name'=>'America/Marigot', 'code'=>'(UTC-04:00) Marigot'),
		    array('name'=>'America/Martinique', 'code'=>'(UTC-04:00) Martinique'),
		    array('name'=>'America/Moncton', 'code'=>'(UTC-04:00) Moncton'),
		    array('name'=>'America/Montserrat', 'code'=>'(UTC-04:00) Montserrat'),
		    array('name'=>'America/Port_of_Spain', 'code'=>'(UTC-04:00) Port of Spain'),
		    array('name'=>'America/Porto_Velho', 'code'=>'(UTC-04:00) Porto Velho'),
		    array('name'=>'America/Puerto_Rico', 'code'=>'(UTC-04:00) Puerto Rico'),
		    array('name'=>'America/Rio_Branco', 'code'=>'(UTC-04:00) Rio Branco'),
		    array('name'=>'America/Santiago', 'code'=>'(UTC-04:00) Santiago'),
		    array('name'=>'America/Santo_Domingo', 'code'=>'(UTC-04:00) Santo Domingo'),
		    array('name'=>'America/St_Barthelemy', 'code'=>'(UTC-04:00) St. Barthelemy'),
		    array('name'=>'America/St_Kitts', 'code'=>'(UTC-04:00) St. Kitts'),
		    array('name'=>'America/St_Lucia', 'code'=>'(UTC-04:00) St. Lucia'),
		    array('name'=>'America/St_Thomas', 'code'=>'(UTC-04:00) St. Thomas'),
		    array('name'=>'America/St_Vincent', 'code'=>'(UTC-04:00) St. Vincent'),
		    array('name'=>'America/Thule', 'code'=>'(UTC-04:00) Thule'),
		    array('name'=>'America/Tortola', 'code'=>'(UTC-04:00) Tortola'),
		    array('name'=>'America/St_Johns', 'code'=>'(UTC-03:30) St. Johns'),
		    array('name'=>'America/Araguaina', 'code'=>'(UTC-03:00) Araguaina'),
		    array('name'=>'America/Bahia', 'code'=>'(UTC-03:00) Bahia'),
		    array('name'=>'America/Belem', 'code'=>'(UTC-03:00) Belem'),
		    array('name'=>'America/Argentina/Buenos_Aires', 'code'=>'(UTC-03:00) Buenos Aires'),
		    array('name'=>'America/Argentina/Catamarca', 'code'=>'(UTC-03:00) Catamarca'),
		    array('name'=>'America/Cayenne', 'code'=>'(UTC-03:00) Cayenne'),
		    array('name'=>'America/Argentina/Cordoba', 'code'=>'(UTC-03:00) Cordoba'),
		    array('name'=>'America/Fortaleza', 'code'=>'(UTC-03:00) Fortaleza'),
		    array('name'=>'America/Godthab', 'code'=>'(UTC-03:00) Godthab'),
		    array('name'=>'America/Argentina/Jujuy', 'code'=>'(UTC-03:00) Jujuy'),
		    array('name'=>'America/Argentina/La_Rioja', 'code'=>'(UTC-03:00) La Rioja'),
		    array('name'=>'America/Maceio', 'code'=>'(UTC-03:00) Maceio'),
		    array('name'=>'America/Argentina/Mendoza', 'code'=>'(UTC-03:00) Mendoza'),
		    array('name'=>'America/Miquelon', 'code'=>'(UTC-03:00) Miquelon'),
		    array('name'=>'America/Montevideo', 'code'=>'(UTC-03:00) Montevideo'),
		    array('name'=>'America/Paramaribo', 'code'=>'(UTC-03:00) Paramaribo'),
		    array('name'=>'America/Recife', 'code'=>'(UTC-03:00) Recife'),
		    array('name'=>'America/Argentina/Rio_Gallegos', 'code'=>'(UTC-03:00) Rio Gallegos'),
		    array('name'=>'America/Argentina/Salta', 'code'=>'(UTC-03:00) Salta'),
		    array('name'=>'America/Argentina/San_Juan', 'code'=>'(UTC-03:00) San Juan'),
		    array('name'=>'America/Argentina/San_Luis', 'code'=>'(UTC-03:00) San Luis'),
		    array('name'=>'America/Santarem', 'code'=>'(UTC-03:00) Santarem'),
		    array('name'=>'America/Sao_Paulo', 'code'=>'(UTC-03:00) Sao Paulo'),
		    array('name'=>'America/Argentina/Tucuman', 'code'=>'(UTC-03:00) Tucuman'),
		    array('name'=>'America/Argentina/Ushuaia', 'code'=>'(UTC-03:00) Ushuaia'),
		    array('name'=>'America/Noronha', 'code'=>'(UTC-02:00) Noronha'),
		    array('name'=>'America/Scoresbysund', 'code'=>'(UTC-01:00) Scoresbysund'),
		    array('name'=>'America/Danmarkshavn', 'code'=>'(UTC+00:00) Danmarkshavn')];
	
	static function listzona(){
		return self::$zonas;
	}//end construct

	static  function getZona(){
		 try {

			return self::listzona();
			 
		 } catch (Exception $e) {
		 	return 0;
		 }
		
	}

}


